CREATE TABLE users (
	id INTEGER NOT NULL AUTO_INCREMENT,
	username VARCHAR(1024) NOT NULL,
	password VARCHAR(1024) NOT NULL,
	disabled tinyint(1) DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)

CREATE TABLE interviews (
	id INTEGER NOT NULL AUTO_INCREMENT,
	send_by INTEGER,
	content VARCHAR(1024) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY(send_by) REFERENCES users (id)
)

CREATE TABLE bookmarks (
	user_id INTEGER NOT NULL,
	interview_id INTEGER NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (user_id, interview_id),
	FOREIGN KEY(user_id) REFERENCES users (id),
	FOREIGN KEY(interview_id) REFERENCES interviews (id)
)
