version: '3'
services:
  mensetsu:
    restart: always
    build: ./tools/python
    container_name: 'mensetsu'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./api:/root/api
    ports:
      - 8000:8000
