version: '3'
services:
  mensetsu:
    restart: always
    build: ./tools/python
    container_name: 'mensetsu'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./api:/root/api
    ports:
      - 8000:8000
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'mensetsu'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./tools/mysql/initdb.d:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
volumes:
  mysql_data:
